spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/mirishop
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  # 이메일 설정
  mail:
    host: smtp.gmail.com
    port: 587
    username: miriemailtest@gmail.com
    password: tznelrsknkkpvmhs
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  redis:
    cache:
      host: localhost
      port: 6379
    auth:
      host: localhost
      port: 6380

  data:
    mongodb:
      uri: mongodb://root:1234@localhost:27017/newsfeed?authSource=admin

  # Multipart 파일 업로드 용량 제한
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 3MB

security:
  jwt:
    secret-key: sudomirishoptokensudomirishoptokensudomirishoptoken  # Base 64 디코딩의경우 _ 언더바 안됨. 주의
    tokenValid-time: 1800000 # 액세스토큰 유효시간 30분
    refreshtokenValid-time: 259200000 # 리프레쉬토큰 유효시간 3일

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

feign:
  user-service:
    url: http://localhost:8080